"""
==========================================================
The document cannot be allowed to drift again
==========================================================

    "as of now different files are carrying different rules set"
                                -- operator, 12 August 2026

Six documents described the trading rules and every one of them was
true the day it was written:

    RULE_BOOK.md      "Rs 1,00,000 per position"   live: Rs 30,000
    RULE_BOOK.md      "ALERT_ONLY = True"          live: False
    RUN_SCHEDULE.md   "full Rs 1 lakh MTF size"    live: Rs 1.2L

Nobody wrote those to mislead. They rotted, quietly, because nothing
ever compared them to the code again.

BOT.md is generated by tools/bot_doc.py, and this test fails the build
when a rule changes and the document is not regenerated. That is the
whole mechanism -- a document that can go stale silently will.
"""

import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / "BOT.md"


def test_bot_doc_exists():
    assert DOC.exists(), (
        "BOT.md is missing. Run: py tools/bot_doc.py --write")


def test_bot_doc_matches_the_running_code():
    """THE POINT. Change a rule without regenerating and this fails."""
    result = subprocess.run(
        [sys.executable, "tools/bot_doc.py", "--check"],
        cwd=str(ROOT), capture_output=True, text=True)
    assert result.returncode == 0, (
        result.stdout + result.stderr
        + "\n\nA rule changed and BOT.md was not regenerated. "
          "Run: py tools/bot_doc.py --write")


def test_the_generated_numbers_are_the_live_ones():
    """Belt and braces: read the values out of the text and compare.

    --check above compares the file to a fresh render, which catches
    drift but would not catch tools/bot_doc.py reading the wrong
    constant in the first place. This asserts against the modules.
    """
    import config
    from core import rules
    text = DOC.read_text(encoding="utf-8")

    assert f"{rules.RISK_PER_TRADE_RS:,.0f}" in text
    assert f"{config.MTF_MARGIN_PER_POSITION_RS:,.0f}" in text
    assert f"{config.DAILY_MAX_LOSS_RS:,.0f}" in text
    assert f"{config.HARD_STOP_FROM_ENTRY_PCT * 100:.2f}%" in text


def test_the_overnight_state_is_stated_correctly():
    """The most expensive fact in the document. If both switches are
    off it must say so LOUDLY, and if one is on it must not."""
    import config
    text = DOC.read_text(encoding="utf-8")
    hole_open = not (config.BROKER_STOP_ENABLED
                     or config.FORCE_SQUARE_OFF_AT_CLOSE)
    warned = "THE OVERNIGHT HOLE IS OPEN" in text
    assert warned == hole_open, (
        "BOT.md's overnight section disagrees with config.py. "
        f"hole_open={hole_open}, document warns={warned}")


@pytest.mark.parametrize("superseded", [
    "RULE_BOOK.md",
    "TRADING_POLICY.md",
    "RULES_TO_TRADE.md",
    "TRADE_SELECTION_RULES.md",
    "STRATEGY.md",
])
def test_every_superseded_document_says_so(superseded):
    """A stale rule book left lying in the root with no warning is how
    somebody sizes a position from Rs 1,00,000 that has been Rs 30,000
    for three weeks. They may stay -- they hold history worth keeping --
    but each must point at the generated one."""
    path = ROOT / superseded
    if not path.exists():
        pytest.skip(f"{superseded} has been removed")
    head = path.read_text(encoding="utf-8", errors="replace")[:600]
    assert "BOT.md" in head, (
        f"{superseded} still reads as current. Put a line at the top "
        f"pointing at BOT.md, which is generated from the code.")
