"""Complete the classification for the 48 stocks whose SECTOR was filled
on 2 September but whose other eight columns were left blank.

core/master_loader.py requires NINE columns on a tradeable row. Filling
one and leaving eight is what stopped the live-path check joining up --
and would have stopped main.py booting.

BUSINESS_TYPE and OWNERSHIP are closed vocabularies and are asserted
against what the file already uses. COMMODITY_EXPOSURE and
ECONOMIC_SENSITIVITY are pipe-separated and also checked term by term,
so a typo cannot introduce a value only one stock has.
"""
import csv
import os

# symbol: (INDUSTRY, CORE BUSINESS, BUSINESS_TYPE, OWNERSHIP,
#          COMMODITY_EXPOSURE, ECONOMIC_SENSITIVITY, KEYWORDS, THEMES)
D = {
"5PAISA": ("DISCOUNT BROKING", "ONLINE DISCOUNT STOCK BROKING AND INVESTMENT PLATFORM", "BROKER", "PRIVATE", "NONE", "INTEREST RATE SENSITIVE", "DISCOUNT BROKING | ONLINE TRADING | DEMAT", "BROKING | CAPITAL MARKETS | FINTECH"),
"ALICON": ("ALUMINIUM CASTINGS", "ALUMINIUM CASTING COMPONENTS FOR AUTOMOBILES", "MANUFACTURER", "PRIVATE", "ALUMINIUM", "CONSUMER DRIVEN", "ALUMINIUM CASTINGS | AUTO COMPONENTS", "AUTO ANCILLARY | ALUMINIUM"),
"AMRUTANJAN": ("OTC HEALTHCARE", "PAIN BALM AND OVER THE COUNTER HEALTHCARE PRODUCTS", "MANUFACTURER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "PAIN BALM | OTC HEALTHCARE", "FMCG | HEALTHCARE"),
"ARDEE": ("SPECIALITY CHEMICALS", "SPECIALITY CHEMICALS AND INTERMEDIATES", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "SPECIALITY CHEMICALS | INTERMEDIATES", "CHEMICALS"),
"ARIES": ("AGRO CHEMICALS", "PLANT MICRONUTRIENTS AND AGRO CHEMICALS", "MANUFACTURER", "PRIVATE", "NONE", "GOVERNMENT SPENDING", "MICRONUTRIENTS | AGRO CHEMICALS", "AGRICULTURE | FERTILIZERS"),
"AVTNPL": ("NATURAL EXTRACTS", "MARIGOLD AND SPICE OLEORESIN EXTRACTS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "OLEORESINS | NATURAL EXTRACTS", "FMCG | EXPORTS"),
"BANARISUG": ("SUGAR MILLING", "SUGAR MANUFACTURING AND CO GENERATION", "MANUFACTURER", "PRIVATE", "SUGAR", "GOVERNMENT SPENDING", "SUGAR | ETHANOL", "SUGAR | ETHANOL"),
"BLUECLOUDS": ("SOFTWARE SERVICES", "SOFTWARE DEVELOPMENT AND IT SERVICES", "SERVICE PROVIDER", "PRIVATE", "NONE", "EXPORT ORIENTED", "SOFTWARE | IT SERVICES", "IT | SOFTWARE"),
"DBOL": ("SUGAR AND BIO REFINERY", "SUGAR ETHANOL AND BIO PRODUCTS", "MANUFACTURER", "PRIVATE", "SUGAR", "GOVERNMENT SPENDING", "SUGAR | ETHANOL | DISTILLERY", "SUGAR | ETHANOL"),
"DCI": ("IT PRODUCT DISTRIBUTION", "DISTRIBUTION OF IT AND NETWORKING PRODUCTS", "DISTRIBUTOR", "PRIVATE", "NONE", "CONSUMER DRIVEN", "IT DISTRIBUTION | NETWORKING", "IT | DISTRIBUTION"),
"DECCANCE": ("CEMENT", "CEMENT MANUFACTURING", "MANUFACTURER", "PRIVATE", "LIMESTONE | COAL", "GOVERNMENT SPENDING", "CEMENT | LIMESTONE", "CEMENT | INFRASTRUCTURE"),
"DHOOTTRANS": ("WIRING HARNESS", "WIRING HARNESSES AND AUTOMOTIVE ELECTRICALS", "MANUFACTURER", "PRIVATE", "COPPER", "CONSUMER DRIVEN", "WIRING HARNESS | AUTO COMPONENTS", "AUTO ANCILLARY | EV"),
"DOLATALGO": ("BROKING", "ALGORITHMIC TRADING AND STOCK BROKING", "BROKER", "PRIVATE", "NONE", "INTEREST RATE SENSITIVE", "ALGO TRADING | BROKING", "BROKING | CAPITAL MARKETS"),
"DOLPHIN": ("OFFSHORE SERVICES", "OFFSHORE SUPPORT AND DIVING SERVICES FOR OIL AND GAS", "SERVICE PROVIDER", "PRIVATE", "CRUDE OIL", "GOVERNMENT SPENDING", "OFFSHORE | OIL SERVICES", "OIL AND GAS | OFFSHORE"),
"ESABINDIA": ("WELDING CONSUMABLES", "WELDING ELECTRODES AND CUTTING EQUIPMENT", "MANUFACTURER", "MNC", "STEEL", "GOVERNMENT SPENDING", "WELDING | ELECTRODES", "CAPITAL GOODS | WELDING"),
"EXCELINDUS": ("SPECIALITY CHEMICALS", "SPECIALITY CHEMICALS AND SOIL ENRICHERS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "SPECIALITY CHEMICALS | AGRO CHEMICALS", "CHEMICALS"),
"FMGOETZE": ("PISTON RINGS", "PISTON RINGS AND ENGINE COMPONENTS", "MANUFACTURER", "MNC", "STEEL", "CONSUMER DRIVEN", "PISTON RINGS | ENGINE COMPONENTS", "AUTO ANCILLARY"),
"FREDUN": ("FORMULATIONS", "PHARMACEUTICAL FORMULATIONS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "FORMULATIONS | PHARMA", "PHARMA | EXPORTS"),
"HINDWAREAP": ("BUILDING PRODUCTS", "SANITARYWARE FAUCETS AND HOME APPLIANCES", "MANUFACTURER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "SANITARYWARE | APPLIANCES", "HOME IMPROVEMENT | CONSUMER"),
"HMAAGRO": ("FOOD PROCESSING", "FROZEN BUFFALO MEAT PROCESSING AND EXPORT", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "FROZEN MEAT | FOOD PROCESSING", "FOOD | EXPORTS"),
"JNPR": ("RENEWABLE POWER", "SOLAR AND WIND POWER GENERATION", "POWER GENERATOR", "PRIVATE", "NONE", "GOVERNMENT SPENDING", "RENEWABLE ENERGY | SOLAR", "RENEWABLES | GREEN ENERGY"),
"JPOLYINVST": ("HOLDING COMPANY", "INVESTMENT AND HOLDING COMPANY", "NBFC", "PRIVATE", "NONE", "INTEREST RATE SENSITIVE", "HOLDING COMPANY | INVESTMENTS", "HOLDING COMPANY"),
"KAMATHOTEL": ("HOTELS", "HOTELS AND RESORTS", "SERVICE PROVIDER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "HOTELS | HOSPITALITY", "HOTELS | TOURISM"),
"LAXMIINDIA": ("NBFC", "MSME AND VEHICLE LENDING", "NBFC", "PRIVATE", "NONE", "INTEREST RATE SENSITIVE", "MSME LENDING | NBFC", "NBFC | LENDING"),
"LEAPIND": ("PALLET POOLING", "PALLET LEASING AND SUPPLY CHAIN SOLUTIONS", "SERVICE PROVIDER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "PALLETS | SUPPLY CHAIN", "LOGISTICS"),
"MAWANASUG": ("SUGAR MILLING", "SUGAR AND DISTILLERY", "MANUFACTURER", "PRIVATE", "SUGAR", "GOVERNMENT SPENDING", "SUGAR | DISTILLERY", "SUGAR | ETHANOL"),
"MIDWESTLTD": ("DIMENSIONAL STONE", "GRANITE AND QUARTZ MINING AND PROCESSING", "MINING", "PRIVATE", "NONE", "EXPORT ORIENTED", "GRANITE | QUARTZ", "MINING | STONE"),
"MIIL": ("CIVIL CONSTRUCTION", "CIVIL CONSTRUCTION AND INFRASTRUCTURE PROJECTS", "EPC / CONTRACTOR", "PRIVATE", "STEEL | CEMENT", "GOVERNMENT SPENDING", "CONSTRUCTION | INFRASTRUCTURE", "INFRASTRUCTURE"),
"MILKYMIST": ("DAIRY", "DAIRY PRODUCTS PANEER AND CHEESE", "MANUFACTURER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "DAIRY | PANEER | CHEESE", "DAIRY | FOOD"),
"MODISONLTD": ("ELECTRICAL CONTACTS", "SILVER ELECTRICAL CONTACTS AND SEMI FABRICATED SILVER", "MANUFACTURER", "PRIVATE", "SILVER", "GOVERNMENT SPENDING", "SILVER CONTACTS | ELECTRICALS", "SILVER | POWER"),
"MOLBIO": ("DIAGNOSTIC DEVICES", "POINT OF CARE MOLECULAR DIAGNOSTIC DEVICES", "MANUFACTURER", "PRIVATE", "NONE", "GOVERNMENT SPENDING", "DIAGNOSTICS | MOLECULAR TESTING", "DIAGNOSTICS | HEALTHCARE"),
"ORIENTBELL": ("CERAMIC TILES", "CERAMIC AND VITRIFIED TILES", "MANUFACTURER", "PRIVATE", "NATURAL GAS", "CONSUMER DRIVEN", "TILES | CERAMICS", "TILES | HOME IMPROVEMENT"),
"PARKHOTELS": ("HOTELS", "LUXURY BOUTIQUE HOTELS", "SERVICE PROVIDER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "HOTELS | HOSPITALITY", "HOTELS | TOURISM"),
"SHREEPUSHK": ("DYES AND FERTILIZERS", "DYE INTERMEDIATES AND SOIL CONDITIONERS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "DYES | FERTILIZERS", "CHEMICALS | AGRICULTURE"),
"SHUKRAPHAR": ("FORMULATIONS", "PHARMACEUTICAL FORMULATIONS", "MANUFACTURER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "FORMULATIONS | PHARMA", "PHARMA"),
"SIGACHI": ("PHARMA EXCIPIENTS", "MICROCRYSTALLINE CELLULOSE AND PHARMA EXCIPIENTS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "EXCIPIENTS | MCC", "PHARMA | EXPORTS"),
"SIMPLEXINF": ("CIVIL CONSTRUCTION", "LARGE SCALE CIVIL ENGINEERING AND CONSTRUCTION", "EPC / CONTRACTOR", "PRIVATE", "STEEL | CEMENT", "GOVERNMENT SPENDING", "CONSTRUCTION | EPC", "INFRASTRUCTURE"),
"SINDHUTRAD": ("COAL LOGISTICS", "COAL TRADING AND MINING LOGISTICS", "SERVICE PROVIDER", "PRIVATE", "COAL", "GOVERNMENT SPENDING", "COAL LOGISTICS | MINING SERVICES", "LOGISTICS | COAL"),
"SPIC": ("FERTILIZERS", "UREA AND FERTILIZER MANUFACTURING", "MANUFACTURER", "PRIVATE", "NATURAL GAS", "GOVERNMENT SPENDING", "UREA | FERTILIZERS", "FERTILIZERS | AGRICULTURE"),
"SURAJEST": ("RESIDENTIAL DEVELOPMENT", "RESIDENTIAL REAL ESTATE DEVELOPMENT", "SERVICE PROVIDER", "PRIVATE", "NONE", "INTEREST RATE SENSITIVE", "HOUSING | REAL ESTATE", "HOUSING | REAL ESTATE"),
"SURAKSHA": ("DIAGNOSTIC CHAIN", "PATHOLOGY AND RADIOLOGY DIAGNOSTIC CHAIN", "SERVICE PROVIDER", "PRIVATE", "NONE", "CONSUMER DRIVEN", "DIAGNOSTICS | PATHOLOGY", "DIAGNOSTICS | HEALTHCARE"),
"SYNCOMF": ("FORMULATIONS", "PHARMACEUTICAL FORMULATIONS AND SOFT GELATIN CAPSULES", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "FORMULATIONS | SOFT GEL", "PHARMA"),
"TECHNOCRAF": ("ENGINEERING PRODUCTS", "DRUM CLOSURES SCAFFOLDING AND ENGINEERING PRODUCTS", "MANUFACTURER", "PRIVATE", "STEEL", "EXPORT ORIENTED", "SCAFFOLDING | DRUM CLOSURES", "ENGINEERING | EXPORTS"),
"THEMISMED": ("FORMULATIONS", "PHARMACEUTICAL FORMULATIONS AND ACTIVE INGREDIENTS", "MANUFACTURER", "PRIVATE", "NONE", "EXPORT ORIENTED", "FORMULATIONS | API", "PHARMA"),
"TNPETRO": ("PETROCHEMICALS", "LINEAR ALKYL BENZENE AND PETROCHEMICALS", "MANUFACTURER", "PSU", "CRUDE OIL", "IMPORT DEPENDENT", "PETROCHEMICALS | LAB", "PETROCHEMICALS"),
"TVSSRICHAK": ("TYRES", "TWO AND THREE WHEELER TYRES", "MANUFACTURER", "PRIVATE", "CRUDE OIL", "CONSUMER DRIVEN", "TYRES | TWO WHEELER", "AUTO ANCILLARY | TYRES"),
"XTRANET": ("IT INFRASTRUCTURE", "NETWORK AND IT INFRASTRUCTURE SOLUTIONS", "SERVICE PROVIDER", "PRIVATE", "NONE", "GOVERNMENT SPENDING", "IT INFRASTRUCTURE | NETWORKING", "IT | GOVERNMENT"),
"ZUARIIND": ("DIVERSIFIED", "SUGAR ETHANOL ENGINEERING AND REAL ESTATE", "MANUFACTURER", "PRIVATE", "SUGAR", "GOVERNMENT SPENDING", "SUGAR | ETHANOL | ENGINEERING", "DIVERSIFIED"),
}

FIELDS = ["INDUSTRY", "CORE BUSINESS", "BUSINESS_TYPE", "OWNERSHIP",
          "COMMODITY_EXPOSURE", "ECONOMIC_SENSITIVITY", "KEYWORDS", "THEMES"]
PATH = "data/master_stocks.csv"


def main():
    with open(PATH, encoding="utf-8", errors="ignore", newline="") as fh:
        rd = csv.DictReader(fh)
        cols = rd.fieldnames
        rows = list(rd)

    def terms(col):
        out = set()
        for r in rows:
            for part in (r.get(col) or "").split("|"):
                if part.strip():
                    out.add(part.strip())
        return out

    # Closed vocabularies: nothing new may be introduced.
    for col, i in (("BUSINESS_TYPE", 2), ("OWNERSHIP", 3)):
        known = terms(col)
        bad = {v[i] for v in D.values() if v[i] not in known}
        if bad:
            raise SystemExit(f"  REFUSING: {col} value not already in use: {bad}")
    # Pipe-separated: every term must already exist.
    for col, i in (("COMMODITY_EXPOSURE", 4), ("ECONOMIC_SENSITIVITY", 5)):
        known = terms(col)
        bad = set()
        for v in D.values():
            for part in v[i].split("|"):
                if part.strip() and part.strip() not in known:
                    bad.add(part.strip())
        if bad:
            raise SystemExit(f"  REFUSING: {col} term not already in use: {bad}")

    done = 0
    for r in rows:
        sym = (r.get("SYMBOL") or "").strip().upper()
        if sym not in D:
            continue
        for name, value in zip(FIELDS, D[sym]):
            if not (r.get(name) or "").strip():
                r[name] = value
        r["SUBSCRIBE"] = "YES"
        r["SUBSCRIBE_REASON"] = ""
        done += 1

    tmp = PATH + ".new"
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)
    os.replace(tmp, PATH)

    yes = sum(1 for r in rows
              if (r.get("SUBSCRIBE") or "").strip().upper() == "YES")
    print(f"  completed and re-enabled: {done}")
    print(f"  universe now            : {yes:,}")


if __name__ == "__main__":
    main()
